### ISSUE TITLE
Feature request - Create badges

### ISSUE THREAD

**Issue by ANONYM-ANONYM** [xHyroM/BeautifulCSS#1]
cc, mohol by si pridat nejake badge nieco podobne ako ma boostrap
 https://getbootstrap.com/docs/4.5/components/badge/
 a este by som uvital aj nieco taketo: https://getbootstrap.com/docs/4.5/components/toasts/

**Comment by ANONYM-ANONYM** [comment]
@xHyroM

**Comment by xhyrom** [comment]
Prepáč za neskorú odpoveď. Myslím si že to nie je zlý nápad! Pridám to

**Comment by chobotnice007** [comment]
> Prepáč za neskorú odpoveď. Myslím si že to nie je zlý nápad! Pridám to

Stejně je to stále ošklivé. @xHyroM
